spring:
  application:
    name: eureka-client

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registry-fetch-interval-seconds: 30
    eureka-server-port: 8761
    fetch-registry: true
    region: us-east-1